### ISSUE TITLE
new release on pypi

### ISSUE THREAD

**Issue by weikang9009** [pysal/mapclassify#10]
We need to have a new release on pypi since the `api.py` is removed now and several packages have `mapclassify` as a dependency. The [last release](https://pypi.org/project/mapclassify/#history) is in August 2017.

**Comment by ljwolf** [comment]
@sjsrey is the only person who can do this. 

https://pypi.org/project/mapclassify/ has only one maintainer. 

I tried, and was rejected by pypi for not being a maintainer.

**Comment by sjsrey** [comment]
I just added @weikang9009 as a maintainer on pypi

**Comment by weikang9009** [comment]
Thanks! I'll publish a release on pypi today.

**Comment by weikang9009** [comment]
We have a new release on pypi: [mapclassify 2.0.0](https://pypi.org/project/mapclassify/2.0.0/)

**Comment by sjsrey** [comment]
Great work @weikang9009 on 2.0.0
