### ISSUE TITLE
Inconsistent UserDefined Scale With Multiple Axes

### ISSUE THREAD

**Issue by gregfeliu** [pysal/mapclassify#109]
I am trying to compare the differences between the number of items in four different data sets using a consistent scale. The issue is that if one of the data sets do not have data in a certain interval, the color scheme will be thrown off and one color will be missing. This means that the color that was supposed to represent the max value for all values (0.46) will now also represent the max value for a different data set (0.2). 

The data was in a GeoDataFrame with data representing each of the four cities in separate columns. I defined a scale that would match the largest value in the four columns and made a number of bins (3 or 4) from 0 to the maximum value. The scale worked well for the column with the largest value, but was incorrect for all of the other columns. 

![Map_of_cities_and_their_regions](https://user-images.githubusercontent.com/36009037/110359968-22fe8300-800c-11eb-9a76-a6132089f6d5.png)

This problem persists no matter how many bins I create, making sure that each column has data within each of the bins I create. 

If there is a better way to create a consistent scale across multiple axes, please let me know. Thank you.

**Comment by martinfleis** [comment]
Hi, this is a known bug in geopandas (https://github.com/geopandas/geopandas/issues/420#issuecomment-772649579), there's nothing to be done about that in mapclassify.

It will have to be fixed in geopandas.
