### ISSUE TITLE
Improving FisherJenks

### ISSUE THREAD

**Issue by cheginit** [pysal/mapclassify#118]
The implemented `FisherJenks` classifier is very slow. I would like to suggest using [jenkspy](https://github.com/mthh/jenkspy) instead. It's written in `cython` and it's very fast.

**Comment by ljwolf** [comment]
Do you happen to have `numba` installed? Our [`FisherJenks` implementation](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L510) should be accelerated using that... we'd definitely invite a rigorous performance comparison there 😄 

Also, the [*Sampled](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L1806) variants are useful in extremely large data, since a random subsample of the target data can often yield the same results. 

Do either of these work for your use case?

**Comment by martinfleis** [comment]
@ljwolf shall we maybe add a warning here https://github.com/pysal/mapclassify/blob/92054a9746c8f7889cc7d61f34cc3ed06cecafa8/mapclassify/classifiers.py#L60 when Numba isn't loaded?

**Comment by cheginit** [comment]
Ah, I didn't notice there's `numba` support. I just gave it a try and compared it with `jenkspy`. I noticed that you're just simply using `jit` without type specification. So I replaced `@jit` with `@njit("f8[:](f8[:], u2, b1)")` and compared the three versions with the following data:

```python
import jenkspy
from mapclassify.classifiers import _fisher_jenks_means
import numpy as np

data = np.random.random(12000) * 5000
data = data.astype("f8")
```

Here are the results.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/13016644/145062410-d29ad7e5-2269-42af-9eba-693e3406e80c.png">

**Comment by cheginit** [comment]
I ran the same test using an array with 120,000  elements instead of 12,000. Here's the results:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/13016644/145074576-69505090-cf5c-48b7-94de-a9c6219a34d2.png">

BTW, I ran these tests on my iMac with 8 cores and 16 G RAM.

**Comment by martinfleis** [comment]
That is interesting!

In any case, I would rather not add `jenskpy` as a dependency here. We don't know how maintained it is and it may be a hassle to install. They offer wheels only for Windows and only up to Python 3.8. I assume that this could cause a lot of friction for users.

**Comment by cheginit** [comment]
Right, it makes sense.

You can shave off a few more seconds by adding cache to `njit` like so `@njit("f8[:](f8[:], u2, b1)", cache=True)`. Feel free to close or if interested, I can modify the code to add the signatures and submit a PR.

**Comment by martinfleis** [comment]
> I can modify the code to add the signatures and submit a PR

That would be very welcome! Thanks!

**Comment by acikmese** [comment]
I would definitely not integrate jenkspy in your environment. Your library works perfectly in my tests, but jenkspy have some problematic outputs. I don't trust to outputs of jenkspy.
