### ISSUE TITLE
change default branch from master to main

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#130]
change default `mapclassify` branch from `master` to `main`.

**Comment by jGaboardi** [comment]
@sjsrey it seems that I don't have admin rights to `mapclassify`. Can you update the settings for this here? And maybe `inequality`, as well? After modernizing `mapclassify`, I think that will be my next focus.

**Comment by sjsrey** [comment]
You should be able to do this now.

**Comment by jGaboardi** [comment]
Done.
