### ISSUE TITLE
remove old/redundant MapClassifier._table_string() method

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#139]
We should consider removing the old [`MapClassifier._table_string()`](https://github.com/pysal/mapclassify/blob/main/mapclassify/classifiers.py#L914) method, which is not used anymore. The updated funcationality is implemented in [`_get_table()`](https://github.com/pysal/mapclassify/blob/main/mapclassify/classifiers.py#L160), which is stand-alone function. We should also consider converting `_get_table()` to a method since it is only called [from within `MapClassifier`](https://github.com/pysal/mapclassify/blob/main/mapclassify/classifiers.py#L844-L852).

**Comment by martinfleis** [comment]
+1 for the removal. Don't mind `_get_table()` either way, it is only internal.

**Comment by jGaboardi** [comment]
Let's leave it where it is now and reevaluate in the future. I'll address the `_table_string()` removal in #135.

**Comment by martinfleis** [comment]
> I'll address the _table_string() removal in https://github.com/pysal/mapclassify/pull/135

Can you keep it as a separate PR? Those are unrelated issues.
