### ISSUE TITLE
warn or raise vs. print statements for unexpected behavior

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#140]
There are 2 places in the code base where `print` statements are used to alert for unexpected behavior. I am of the opinion that these should throw a `warning` (case 1) and raise an `exception` (case 2).

1. [This](https://github.com/pysal/mapclassify/blob/a7770fb98bf945dad3c62ccf2c0f8b53abb1774a/mapclassify/classifiers.py#L1635-L1636) should probably throw a `warning`.
2. [This](https://github.com/pysal/mapclassify/blob/a7770fb98bf945dad3c62ccf2c0f8b53abb1774a/mapclassify/pooling.py#L82-L84) should probably raise a `ValueError`.

**Comment by martinfleis** [comment]
Yes and yes.
