### ISSUE TITLE
`MaxP.update()` – bins used by not defined

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#142]
In https://github.com/pysal/mapclassify/commit/85057955b6828725224231019c791df5b15b678f I commented out the [`update`](https://github.com/pysal/mapclassify/blob/a7770fb98bf945dad3c62ccf2c0f8b53abb1774a/mapclassify/classifiers.py#L2576-L2599) method for `MaxP` due to linting failure, and then tests were passing without it. The linting was failing because `bins` is used but never passed in or defined within. I am wondering if this is a bug introduced through copy-paste  of another classifier's `update` method, for example [`UserDefined`](https://github.com/pysal/mapclassify/blob/main/mapclassify/classifiers.py#L2337)?

**Comment by sjsrey** [comment]
We can remove the `update` method for MaxP. Doing so will have it use the inherited `update` method which will simply reclassify the extended array. I think the listing error was due to an errant cut and paste.
