### ISSUE TITLE
remove spaces from title of classifier table string

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#145]
The [spaces added to the title of classifier table strings](https://github.com/pysal/mapclassify/blob/5c9680ae7d10ec762ebbc77a5dc7f9a838e2065c/mapclassify/classifiers.py#L186) are causing linting to fail when updating docstring. I can see no reason no to get rid of those extra spaces (tests are passing locally without the spaces in the string repr).

It's a minor thing, but I vote for removing.

**Comment by sjsrey** [comment]
We need the three spaces for table alignment. Would #152 take care of the linter issue?
