### ISSUE TITLE
silence warnings option when `k` classes not possible?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#149]
I propose adding a `silence_warnings` keyword à la [`libpysal.W`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L42) for scenarios where `k` classes can't be achieved. For example, [here](https://github.com/pysal/mapclassify/blob/5c9680ae7d10ec762ebbc77a5dc7f9a838e2065c/mapclassify/classifiers.py#L255-L259) in `quantiles()`.

**Comment by martinfleis** [comment]
Not sure about that. In lib you sometimes simply know that there are islands. Here, if you knew you'd probably set a correct k. So we warn that something unexpected happened while lib just silences warnings you would expect. In which case are you running into these? Is it frequent?

**Comment by jGaboardi** [comment]
I'm not married to the idea, and after thinking about it a bit more it is more likely that the user would want a visible warning compared to libpysal islands, as you said. I think it is safe to close this and then if another situation is apparent in the future, we can revisit.
