### ISSUE TITLE
`v2.5.0` release

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#160]
I'd like to cut a fresh release (`v2.5.0`?)  for this month's PySAL meta release. Anything else to add/adjust/etc. before that?

**Comment by martinfleis** [comment]
Fine with me as is.

**Comment by jGaboardi** [comment]
`v2.5.0rc1` [docs](https://pysal.org/mapclassify/index.html) are live. And version is out on `pip`.

**Comment by sjsrey** [comment]
Some of the links a broken with the change from `master` to `main` as the default branch. Click the images at:

https://pysal.org/mapclassify/index.html

**Comment by jGaboardi** [comment]
> Some of the links a broken with the change from `master` to `main` as the default branch. Click the images at:
> 
> https://pysal.org/mapclassify/index.html

Good catch!

**Comment by jGaboardi** [comment]
@sjsrey I just noticed that all three links go to the same notebook; there are simply 3 different PNGs. This was going back to at least the last release. I am assuming it's desired behavior?

**Comment by sjsrey** [comment]
yes - the notebook demonstrates the ability to change the options to generate different classifications.

**Comment by jGaboardi** [comment]
`v2.5.0rc2` [docs](https://pysal.org/mapclassify/index.html) are live. And version is out on [`pip`](https://pypi.org/project/mapclassify/2.5.0rc2/).

**Comment by jGaboardi** [comment]
I'll cut the `v2.5.0` once we're satisfied.

**Comment by jGaboardi** [comment]
confirmed #167 works as no PR was opened with [`v2.5.0rc3`](https://github.com/pysal/mapclassify/actions/runs/3916808032/jobs/6696189881).

**Comment by jGaboardi** [comment]
`v2.5.0` is cut.

**Comment by jGaboardi** [comment]
Might want to consider a `v2.5.1` patch release after #168 is merged.
