### ISSUE TITLE
gadf and K_classifiers not in __ini__.py

### ISSUE THREAD

**Issue by weikang9009** [pysal/mapclassify#18]
Just wondering if utility functions [gadf](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L2268) and [K_classifiers](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L2340) should be included in  [ `__ini__.py`](https://github.com/pysal/mapclassify/blob/master/mapclassify/__init__.py)

**Comment by sjsrey** [comment]
Good catch. Added in #20
