### ISSUE TITLE
modernize infrastructure (2023/09)

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#190]
*  [x] swap `versioneer` for `setuptool_scm` – [9764687](https://github.com/pysal/mapclassify/pull/193/commits/97646872ff8db39f79a7fac8532a79b35ea9db87)
* [x] migrate to `pyproject.toml` – [d55f7de](https://github.com/pysal/mapclassify/pull/193/commits/d55f7deac08321f446c4a739e3bdccfd3d1983f2)
* [x] update `pre-commit-config` – [c2fa127](https://github.com/pysal/mapclassify/pull/193/commits/c2fa12729b9f0f2f945eb4625b8b36f567de5338)
* [x] drop 3.8 testing (thoughts @martinfleis? maybe too soon?) – [15c6118](https://github.com/pysal/mapclassify/pull/193/commits/15c61189b45f2ba08375b6d9ed4f8d4ec2a333be)
* [x] add 3.11 testing with `numba` – [83ebfa6](https://github.com/pysal/mapclassify/pull/193/commits/83ebfa614a2890a67add2066a2c58bd3b736bf9e)
* [x] review & update workflows as needed – [15c6118](https://github.com/pysal/mapclassify/pull/193/commits/15c61189b45f2ba08375b6d9ed4f8d4ec2a333be)
* [x] purge superfluous files – [d55f7de](https://github.com/pysal/mapclassify/pull/193/commits/d55f7deac08321f446c4a739e3bdccfd3d1983f2)

**Comment by martinfleis** [comment]
> drop 3.8 testing (thoughts @martinfleis? maybe too soon?)

nope, we're actually late :). 3.9 shall be dropped soon in fact -> https://scientific-python.org/specs/spec-0000/
