### ISSUE TITLE
chorobrewer branch has begun

### ISSUE THREAD

**Issue by sjsrey** [pysal/mapclassify#27]
For more details on this visualization component for demonstrating mapclassify see the [design document/discussions](https://hackmd.io/3HRsBnmDTRaDu9xFPuxiNQ)

**Comment by darribas** [comment]
Wow, this is cool!!!

**Comment by sjsrey** [comment]
- Wei - Color ramp selector
- Renan - Widget exploration
- Stef - map generation
- Serge - color scheme integration and constraints

**Comment by sjsrey** [comment]
This has moved into the [tutorial](https://github.com/sjsrey/mapclassify/blob/choro/notebooks/03_choropleth.ipynb).
