### ISSUE TITLE
Backwards compatability

### ISSUE THREAD

**Issue by rando2** [pysal/mapclassify#48]
For others who may stumble onto this same issue, I just wanted to make the note that Mapclassify will work with Python 2.7 if you clone the repository, make one small change to setup.py (add the line "from io import open"), and run pip install with the -e parameter pointing to your local version of the repository (e.g., python2 -m pip install -e ~/my_packages/mapclassify).

My experience has been that some of the other packages useful for choropleth visualizations are not compatible with Python3, so it's great that Mapclassify can work in both.

Thank you for making this excellent tool!

**Comment by ljwolf** [comment]
Hi,

Which packages are you referring to that are not compatible with Python 3?

**Comment by ljwolf** [comment]
I should also say, thanks for the note! I hope this helps others in a similar position.

But, we cannot guarantee that the package will continue to be compatible with Python 2 for any appreciable period of time, and we recommend [users of Python 2 to upgrade as soon as possible...](https://python3statement.org/) While most of the code should be compatible, the tests are not run on python 2.
