### ISSUE TITLE
Add a Pooled classifier

### ISSUE THREAD

**Issue by sjsrey** [pysal/mapclassify#51]
For panel data, keeping the bins constant across periods and defined on the vectorized panel would facilitate snapshot comparisons:

![image](https://user-images.githubusercontent.com/118042/67827846-6fd46000-fa8e-11e9-855e-b94d5f2dbaeb.png)

Source: PySAL Gitter 2019-10-29.

**Comment by jGaboardi** [comment]
@ResidentMario

**Comment by sjsrey** [comment]
- [ ] add notebook demonstrating pooling
- [ ] add notebook to tutorial on api page
