### ISSUE TITLE
Extra files in PyPI sdist

### ISSUE THREAD

**Issue by QuLogic** [pysal/mapclassify#56]
Besides missing a few documentation files (this is arguable, though lacking `README.md` seems unfortunate), the sdist seems to contain a few extra files:
* `mapclassify/deprecation.py`
* `mapclassify/flycheck_classifiers (serges-MacBook-Pro.local's conflicted copy 2019-07-03).py`
* `mapclassify/test.py`

**Comment by sjsrey** [comment]
Ensure the release build doesn't reproduce this error.
