### ISSUE TITLE
Error while running mapclassify

### ISSUE THREAD

**Issue by 1030ahmad1030** [pysal/mapclassify#60]
AttributeError: module 'mapclassify' has no attribute 'Fisher_Jenks'

**Comment by weikang9009** [comment]
Hello, the class has been renamed from `Fisher_Jenks` to `FisherJenks`. If you go to [`mapclassify`'s documentation website](https://pysal.org/mapclassify/index.html) and navigate to the API page, you will find the current classifiers and their names:
![image](https://user-images.githubusercontent.com/7359284/77351977-b6f01580-6cfb-11ea-884c-2a775555aba9.png)

**Comment by 1030ahmad1030** [comment]
Thank you very much
