### ISSUE TITLE
Difference between Natural Breaks and Fisher Jenks schemes

### ISSUE THREAD

**Issue by PyMap** [pysal/mapclassify#62]
Hi all! I'm working with some census data to build choroplet maps and I'm wondering what is the difference between the natural breaks and fisher jenks schemes. As far as I know, both of them reduce the variance inside the classification group and also between classification groups. But I'm not getting the detailed difference among both methods.

I was looking into the examples that are pointed out in the implementation section here in the repo and they look pretty similar. And here I share another one with the data I'm using now:

![image (3)](https://user-images.githubusercontent.com/44501803/79818019-268a0c80-835d-11ea-83ed-d1ec2d3f48b4.png)

As the results using both methods are very similar I'm wondering if Is the Fisher Jenks method a kind of optimization of the Natural Breaks scheme?

Many thanks for your help!

**Comment by sjsrey** [comment]
In mapclassify, NaturalBreaks is essentially k-means, while FisherJenks is a different optimization approach that will dominate NB in terms of internal homogeneity.

**Comment by PyMap** [comment]
When you say that Fisher Jenks dominates Natural Breaks in terms of internal homogeneity that means that both are mean based but in the first one prevales the mean distance inside the k clusters, while in the last one both internal (inside the group) and external (between groups) distances interms of the array values have the same weight? 

Do you have any documentation where I can read a little more about it or see how each classification method calculates the cutoff values of the intervals? 

Thanks!

**Comment by sjsrey** [comment]
Have a look at the [chapter](https://geographicdata.science/book/notebooks/05_choropleth.html) in a draft book we are writing on geographic data science with python.

**Comment by PyMap** [comment]
Hey @sjsrey, If I'm correctly catching what you explained above, when Natural Breaks uses the [sklearn implementarion](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L8), that should mean that the classification is woking over the 1dim array of values (that is passed as parameter `mapclassify.NaturalBreaks(values, k=n)`) by  selecting a **k** number of centroids, assigning each value in the array to the nearest center and finding new centroids by taking the average of all the points assigned to each cluster. 

What I've also getting when you says that Fisher jenks is an optimizaion of NB is that the main difference is tha the way in which [classes (k) are built looks for internal homogeneity inside the class and external heterogeneity between classest](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L519-L520)

Looking in more detail [how this implementation works](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L532-L562), I see that there are two matrix: one to store the value id inside the ordered array and the other to store the sum of standard deviations between them. For example, If I would have,let'say, the following array:

`[10,14,30,31,32]`

the classifier will iterate and build both matrix over the following combinations:

14: 14 - 10\
 30: 30 - 14 - 10
 31: 31 - 30 - 14 - 10
 32: 32 - 31 - 30 - 14 - 10


The sum of the std will be estimated taking the len of each combination and the id of each value in the array stored in the first matrix to find the limit or break of each class. In this case, if we would specify `k=2`, we would have `14` as first limit and `32` as second.

If the description above is correct I think I'm getting the difference between Natural Breaks and a mean-based optimization (Fisher-Jenks).

Thanks for your comments and help!
