### ISSUE TITLE
 current version of mapclassify in docs? 

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mapclassify#70]
The docs list the current version of `mapclassify` as `v2.1.1`. The current (pre) released version is [`v2.3.0`](https://github.com/pysal/mapclassify/blob/a70dd99aee5b39660507d618d1ec0858f1d2155f/mapclassify/__init__.py#L1). Should the docs be rebuilt now or after the official release of `v2.3.0`? If the docs should be rebuilt now, I'll go ahead and make a PR.

**Comment by sjsrey** [comment]
I think we should wait for the release of 2.3. I have a start on updating the docs in #66.

**Comment by jGaboardi** [comment]
resolved via #78
