### ISSUE TITLE
`sys` import missing from setup.py

### ISSUE THREAD

**Issue by knaaptime** [pysal/mapclassify#73]
currently a development install of mapclassify will fail because the `sys` module is used on [this line](https://github.com/pysal/mapclassify/blob/68e0d2b63a8982016496307753c710f08b0ed591/setup.py#L17) but it's never imported

**Comment by sjsrey** [comment]
See https://github.com/pysal/mapclassify/pull/66/commits/d2c7d97f683cd854e6d344c9f11d9a73d3af61d8
